name: Unit Tests & Coverage

on: [push]

jobs:
  Code-Coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.2
        mongodb-version:
          - 3.6.3
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@master
        with:
          tools: composer:v2
          php-version: ${{ matrix.php-version }}
          extensions: "json, mbstring, mongodb, pdo"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: commlink
          mongodb-password: secret-password
          mongodb-db: commlink-test

      - name: "Install Composer dependencies & app config"
        run: |
          cp .github/workflows/env.testing .env.testing
          cp .github/workflows/env.testing .env
          composer install --no-progress --no-interaction

      - name: "Execute unit tests with code coverage"
        run: vendor/bin/phpunit --coverage-html coverage --coverage-clover 'coverage/clover.xml'

      - name: "Upload test coverage"
        uses: actions/upload-artifact@v3
        with:
          name: Test Coverage Report
          path: ./coverage/

      - name: "Comment coverage report"
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: ./coverage/clover.xml

      - name: "Retrieve the logs"
        if: ${{ failure() }}
        run: cat storage/logs/*
