name: Unit Tests & Coverage

on: [push]

jobs:
  Code-Coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.2
        mongodb-version:
          - 3.6.3
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@master
        with:
          tools: composer:v2
          php-version: ${{ matrix.php-version }}
          extensions: "json, mbstring, mongodb, pdo"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: commlink
          mongodb-password: secret-password
          mongodb-db: commlink-test

      - name: "Install Composer dependencies & app config"
        run: |
          cp .github/workflows/env.testing .env.testing
          cp .github/workflows/env.testing .env
          composer install --no-progress --no-interaction

      - name: "Execute unit tests with code coverage"
        run: vendor/bin/phpunit --coverage-clover public/coverage/clover.xml

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: public/coverage/clover.xml
          threshold_alert: 80
          threshold_warning: 95

      - name: "Retrieve the logs"
        if: ${{ failure() }}
        run: cat storage/logs/*
