name: Documentation

permissions:
  contents: read

on:
  push:
    paths:
      - 'public/openapi/**'

jobs:
  openapi-lint:
    name: Validate OpenAPI spec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Validate OpenAPI spec
        run: npx @redocly/cli lint public/openapi/openapi.yml
