name: PHP Static Analysis

on: pull_request

jobs:
  PHP-Code-Sniffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install PHP Code Sniffer"
        run: COMPOSER=.github/workflows/composer.phpcs.json composer install --no-interaction --no-progress

      - uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php"
          phpcs_path: vendor/bin/phpcs
          standard: phpcs.xml

  PHP-CS-Fixer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.1
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP w/ Extensions"
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: "json, mbstring, mongodb, pdo"

      - name: "Install PHP CS Fixer"
        run: COMPOSER=.github/workflows/composer.php-cs-fixer.json composer install --no-interaction --no-progress

      - name: "Run php-cs-fixer"
        run: vendor/bin/php-cs-fixer fix --dry-run --config=./php_cs.php -v --using-cache=no --diff --ansi

  PHPStan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.2
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP w/ Extensions"
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: "json, mbstring, mongodb, pdo"

      - name: "Install Composer dependencies & app config"
        run: |
          cp .github/workflows/env.testing .env.testing
          cp .github/workflows/env.testing .env
          composer install --no-progress --no-interaction
          composer install --no-progress --no-interaction

      - name: "Run PHPStan analysis"
        run: vendor/bin/phpstan analyze
